apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - patch-cm-cni-conflist.yaml
  - patch-ds-cni-conflist-writer.yaml

patchesStrategicMerge:
  - patch-istio-cni-config.yaml
  - patch-flannel-remove-install-cni.yaml
