apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: istio-cni-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: istio-cni-node
  template:
    metadata:
      labels:
        k8s-app: istio-cni-node
    spec:
      containers:
        - name: install-cni
          env:
            - name: CNI_CONF_NAME
              value: "10-calico.conflist"
