apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server
          env:
            - name: OBJECTSTORECONFIG_HOST
              value: minio-service.kubeflow.svc.cluster.local
            - name: OBJECTSTORECONFIG_PORT
              value: "9000"
            - name: OBJECTSTORECONFIG_REGION
              value: us-east-1
            - name: OBJECTSTORECONFIG_SECURE
              value: "false"
